### ISSUE TITLE
Futurewarning

### ISSUE THREAD

**Issue by BeFygo** [mduran80/daikin_madoka#18]
Hi,

The daikin_madoka integration work fine with HA 2022.8.2 but trows the error noted below:

  connected = await self.client.is_connected()
/usr/local/lib/python3.10/site-packages/pymadoka/connection.py:163: FutureWarning: is_connected has been changed to a property. Calling it as an async method will be removed in a future version
  DISCOVERED_DEVICES_CACHE = await scanner.get_discovered_devices()
/usr/local/lib/python3.10/site-packages/pymadoka/connection.py:56: FutureWarning: This method will be removed in a future version of Bleak. Use the `discovered_devices` property instead.

Upgrading to HA 2022.9.4 the integration doesn't connect to the device anymore.

Maybe repairing fixes this, but I did not have the time yet to try.

Update: Even repairing the device doesn't work

**Comment by mduran80** [comment]
I will have a look at the version uograde when I find some time (soon,
hopefully).

The FutureWarnings have already been adressed in the pymadoka library,
although I haven’t released the version yet until I can do more testing.

Since HA started using  bleak too, more compatibility issues may arise and
affect pymadoka stability.

**Comment by mduran80** [comment]
I just updated my HA and base OS and the integration is working as expected. However, take into account that HA updates may require to repeat all the bluetoothctl process so the info in the D-BUS is updated.

Tested with:

Home Assistant 2022.9.6
Supervisor 2022.09.1
Operating System 8.5
Frontend 20220907.2 - latest

Please connect via shell and remove the device: 

1. Run bluetoothctl 
2. Type remove <mac>
3. If the integration is running in HA, the bluetootctl client should immediately show the connection confirmation request with the pair code, just accept it and rush to the thermostat to accept it too.
4. The integration should work and show as available

**Comment by mduran80** [comment]
I am using a TP-link UB400 myself. The conflicts might be caused because HA
started to use bleak for the BT and its version was higher than pymadoka’s
but should be fine now.

**Comment by BeFygo** [comment]
Oke, I'll wait with ordering a new adapter and keep you posted.

**Comment by BeFygo** [comment]
Hi,

Yesterday i noticed that the AC became "unavailable" several times en sometimes it stayed "available" but didn't represent the real status.
Meaning that it would say its "off" while in realtime it was in "heat" mode (activated by the madoka thermostat).

So with my setup and HA 2022.9.6 madoka is unstable.

Setup:
OMV 6
Version: 6.0.41-1 (Shaitan)
Kernel: Linux 5.18.0-0.deb11.4-amd64
HA: Docker
Bluetooth adapter: TP-link UB500
