### ISSUE TITLE
BROKEN after update [HA 2022.10.1 , OS 9.0]

### ISSUE THREAD

**Issue by rawframe** [mduran80/daikin_madoka#22]
### Updated to:

Home Assistant 2022.10.1
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221006.0 - latest

### **_Stopped working so I tried:_**

1. Unpaired all bluetooth pairings, then rebooted.
2. Deleted Madoka software from custom_components, then rebooted.
3. Re-installed Madoka software to custom_components, then rebooted.
4. Paired Madoka with HCI0 default bluetooth adapter successfully, then rebooted. (Checked hci0 was correct).
5. Added Madoka integration in HA.
6. **Entered mac address but it always FAILS.** 

What are the ticks are for?
What is the number 5 at the bottom for?
Tried turning ticks on and off and entering  only one mac address in lower case, upper case, and in quotes ('') but nothing works.
Tried disabling HA bluetooth integration also.

### **_Can you please help_**, has been great for many years, I need this software to work!

**Comment by mduran80** [comment]
Hi,

I just fixed the bleak error and bumped pymadoka library version. You should either download the component again or update the manifest to reflect the change on the pymadoka dependency. (from  "== 0.2.5" to ">=0.2.6" .

All the UI messages should appear in the integration.

The number 5 reflects for how long the devices discovery is to be run.
The tick is to force disconnection so the discovery runs without problem.

**Comment by carrilero94** [comment]
> Hi,
> 
> I just fixed the bleak error and bumped pymadoka library version. You should either download the component again or update the manifest to reflect the change on the pymadoka dependency. (from "== 0.2.5" to ">=0.2.6" .
> 
> All the UI messages should appear in the integration.
> 
> The number 5 reflects for how long the devices discovery is to be run. The tick is to force disconnection so the discovery runs without problem.

Changing the dependency in the manifest.json solved my problem automatically. Thank you so much!
