### ISSUE TITLE
Would I be able to use integration and Daikin app at the same time?

### ISSUE THREAD

**Issue by Szymek887** [mduran80/daikin_madoka#23]
Hello, I really appreciate your work, but I have a question. According to documentation I need to disconnect controller from Daikin app in order to connect it to HomeAssistant. When I connect it with HA would I still be able to connect to it from Daikin app? I need to have it integrated with Daikin app and I want to use HA integration as an add-on

Thank you very much!

**Comment by mduran80** [comment]
Hi,

Unfortunately not, it is not possible. The thermostat needs to connect to a single "master" which can be HomeAssistant or the phone app.
