### ISSUE TITLE
integration with ESPHome Bluetooth proxy

### ISSUE THREAD

**Issue by trantoriana** [mduran80/daikin_madoka#24]
Hi,

Rather than a BT stick attached to the HA machine I use the ESPHome BT proxy.

Anyone know how to do the pairing in this situation?
If I use the terminal and the bluetoothctl there is no local controller, so 'list' does not show a controller.
scan on/off always show no default controller available.

How to do the pairing in the case of using a ESPHome proxy?

Thanks, Trant

**Comment by trantoriana** [comment]
Never mind... found the answer..

Proxy cannot be used as communication is bi directional which proxy does not support.

**Comment by SheGe** [comment]
ESPHome started supporting active connections:

> active (Optional, boolean): Enables proxying active connections. Defaults to false. Requires Home Assistant 2022.10 or later.

<https://esphome.io/components/bluetooth_proxy.html>

what makes asked question valid again.

**Comment by mario-tux** [comment]
Yes, reopen it as it make sense. @mduran80

**Comment by mduran80** [comment]
I just asked in the HA devs_bluetooth support channel and it is not supported yet.

<img width="1280" alt="Screenshot 2022-12-16 at 11 07 17" src="https://user-images.githubusercontent.com/22393167/208075573-080fe264-0733-40c1-9172-cdd3d86865c7.png">
