### ISSUE TITLE
Using ESPHome proxy?

### ISSUE THREAD

**Issue by BeFygo** [mduran80/daikin_madoka#27]
Hi @mduran80 ,

What do you think about the possibility of using ESPHome bluetooth_proxy for communicating instead of a usb dongle?

**Comment by mduran80** [comment]
It will not work, I already asked on the HA bluetooth dev channel. The best
chance is to use Raspberry Pi Zero or similar with pymadoka + MQTT.

**Comment by BeFygo** [comment]
Today I have been fiddling with ESPHome proxy and HA bluetooth (and BLE) tracking.
Suddenly madoka cannot connect Through the USB dongle because ESPHome keeps overruling the dongle and connects to the daikin device.

Offcourse several errors occure without the propper 'pairing code' procedure.
