### ISSUE TITLE
Using integration with Shelly gen 2 Bluetooth Proxy 

### ISSUE THREAD

**Issue by acseven** [mduran80/daikin_madoka#29]
I've tried to connect to some devices using Shelly gen 2's Bluetooth Proxy feature, both in active and passive mode, but only local bluetooth devices can be scanned. Is this the case?

https://www.home-assistant.io/integrations/shelly/#bluetooth-support

> Bluetooth Support
> Shelly generation 2 devices running firmware 0.12 or later can act as a Bluetooth proxy for advertisements. Active or passive listening can be enabled in the options flow.

**Comment by mduran80** [comment]
This will not work, HA's bluetooth proxy doesn't support authentication at the moment

**Comment by pmpinto** [comment]
Hey @mduran80 is that still the case? I'm trying to add a Madoka controller through a Shelly 2PM Gen 3, but I'm stuck at the "Bluetooth local adapter name", as `hci0` doesn't work nor does `hci1`, `…2`, `…3` etc. What should I put in this field?
