### ISSUE TITLE
Does not work on 2021.6

### ISSUE THREAD

**Issue by raypanggh** [mduran80/daikin_madoka#5]
Does not work on 2021.6 due to the new requirement to have a valid version key.

**Comment by pacomm** [comment]
It's easy, until its integration in the official version you can edit "manifest.json" and add this line:
`  "version": "0.9.9"`

**Comment by RoomControl18** [comment]
Is there any sollutions to this?. I am not able to install the add on. I have coy the folder in "custom_components", but i can't add the device. 

I can pair using bluetoothctl with Madoka, but i can't view the card or device in Home Assistant.

I have try to add "version": "0.9.9" but it doesn´t work.
