### ISSUE TITLE
Integration in core?

### ISSUE THREAD

**Issue by pykateb** [mduran80/daikin_madoka#6]
Hi,
Does the integration into the core integration is effective?

Great work :!!!

**Comment by mduran80** [comment]
Hi!

I submitted it for review a long time ago, but I haven’t checked if it has been merged already. It was working perfectly by the time with all the tests passing and 100% code coverage.

If you download the code and copy it into the core folder, it should work.

**Comment by pykateb** [comment]
Thank you!
And most of all, thank you for your work!
